export const escape=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const icon=(name)=>{
 const paths={arrow:'M5 12h14m-6-6 6 6-6 6',back:'M19 12H5m6-6-6 6 6 6',save:'M5 3h12l4 4v14H3V3h2m2 0v7h10V3M7 21v-7h10v7',clock:'M12 8v5l3 2',close:'m6 6 12 12M6 18 18 6',check:'m5 12 4 4L19 6',flag:'M5 21V3m0 1c5-4 9 4 14 0v10c-5 4-9-4-14 0',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',plus:'M12 5v14M5 12h14',info:'M12 11v6m0-10v1',shield:'M12 3 3 6v6c0 5 9 9 9 9s9-4 9-9V6l-9-3',folder:'M3 6V4h7l2 3h9v13H3V6',dots:'M5 12h.1M12 12h.1M19 12h.1'};
 return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${['clock','info'].includes(name)?'<circle cx="12" cy="12" r="9"/>':''}<path d="${paths[name]||paths.info}"/></svg>`;
};
export const logo=`<svg viewBox="0 0 48 48" aria-hidden="true"><rect width="48" height="48" rx="13" fill="#243b91"/><path fill="#fff" d="M11 11h11v11H11zm15 0h11v11H26zM11 26h11v11H11z"/><path fill="#a7b7f3" d="M26 26h11v11H26z"/></svg>`;
export function tile(v,large=false){const n=v.n||3,cell=30,size=n*cell,pad=4;return `<svg class="tile${large?' large':''}" viewBox="0 0 ${size} ${size}" role="img" aria-label="${n} by ${n} tile. Filled positions, row then column: ${Array.from({length:n*n},(_,i)=>v.mask&(1<<i)?`${Math.floor(i/n)+1}-${i%n+1}`:null).filter(Boolean).join(', ')||'none'}"><rect width="${size}" height="${size}" rx="5" fill="#eef1f5"/>${Array.from({length:n*n},(_,i)=>`<rect x="${i%n*cell+pad}" y="${Math.floor(i/n)*cell+pad}" width="${cell-pad*2}" height="${cell-pad*2}" rx="2" fill="${v.mask&(1<<i)?'#203956':'#fff'}"/>`).join('')}</svg>`;}
export function stimulus(s){
 if(s.kind==='matrix')return `<div class="matrix">${s.cells.map(v=>v===null?'<div class="missing" aria-label="Missing tile">?</div>':tile(v)).join('')}</div>`;
 if(s.kind==='numberMatrix')return `<div class="number-matrix">${s.cells.map(v=>`<span${v===null?' class="missing"':''}>${v??'?'}</span>`).join('')}</div>`;
 if(s.kind==='single')return `<div class="single-tile">${tile(s.tile,true)}</div>`;
 if(s.kind==='fold')return `<div class="fold-tile">${tile(s.tile,true)}<span class="fold-line" aria-hidden="true"></span>${s.double?'<span class="fold-line-horizontal" aria-hidden="true"></span>':''}</div><p class="caption">${s.double?'Folded top-left quarter · dashed lines show both folds':'Folded left half · dashed line is the fold'}</p>`;
 if(s.kind==='cube'){const p=[[1,0],[0,1],[1,1],[2,1],[1,2],[1,3]];return `<div class="cube-net" role="img" aria-label="Cube net: top ${s.faces[0]}; next row ${s.faces[1]}, ${s.faces[2]}, ${s.faces[3]}; below center ${s.faces[4]}; bottom ${s.faces[5]}">${s.faces.map((n,i)=>`<span style="grid-column:${p[i][0]+1};grid-row:${p[i][1]+1}">${n}</span>`).join('')}</div>`;}
 if(s.kind==='sequence')return `<div class="sequence">${s.values.map(v=>`<span>${v}</span>`).join('<span class="separator">·</span>')}<span class="sequence-question">?</span></div>`;
 if(s.kind==='facts')return `<div class="facts">${s.lines.map(l=>`<p>${escape(l)}</p>`).join('')}</div>`;
 if(s.kind==='ratio')return `<div class="ratio">${s.values[0]} : ${s.values[1]} <span>=</span> ${s.values[2]} : ?</div>`;
 return `<div class="equation">${escape(s.text)}</div>`;
}
export function compass(x=null,y=null){return `<div class="compass-wrap"><div class="axis-top">More authority</div><div class="compass" role="img" aria-label="${x===null?'Economic and governance compass; no result yet':`Economic axis ${x.toFixed(1)}; governance axis ${y.toFixed(1)}. Both axes range from minus ten to ten.`}"><span class="quad tl">Public economy<br>Collective authority</span><span class="quad tr">Market economy<br>Collective authority</span><span class="quad bl">Public economy<br>Individual safeguards</span><span class="quad br">Market economy<br>Individual safeguards</span><div class="cross-x"></div><div class="cross-y"></div>${x!==null?`<span class="compass-dot" style="left:${(x+10)*5}%;top:${(10-y)*5}%"></span>`:''}</div><div class="axis-bottom">More individual safeguards</div><div class="compass-labels"><span>← Public provision</span><span>Market allocation →</span></div></div>`;}
export function introArt(type){
 if(type==='politics')return compass();
 if(type==='personality')return `<div class="trait-art" aria-hidden="true"><svg viewBox="0 0 300 240">${[96,78,60,42,24].map((r,i)=>`<circle cx="150" cy="120" r="${r}" fill="none" stroke="${['#243b91','#4564c3','#7992d4','#a7b8e1','#d1dbef'][i]}" stroke-width="11" stroke-dasharray="${r*4.7} ${r*1.58}" transform="rotate(${[-70,-25,15,55,95][i]} 150 120)"/>`).join('')}</svg><div class="art-caption">FIVE TRAITS. THIRTY FACETS.</div></div>`;
 if(type==='iq')return `<div class="iq-art" aria-hidden="true"><div class="mini-matrix">${[1,3,2,5,6,3,4,5,null].map((v,i)=>v===null?'<span class="missing">?</span>':tile({mask:[273,84,357,325,234,431,305,78][i],n:3})).join('')}</div><div class="art-caption">FIVE WAYS TO REASON.</div></div>`;
 return `<div class="dark-art" aria-hidden="true"><svg viewBox="0 0 300 240"><circle cx="150" cy="87" r="58" fill="#72568f" fill-opacity=".2" stroke="#72568f" stroke-width="1.5"/><circle cx="110" cy="151" r="58" fill="#72568f" fill-opacity=".2" stroke="#72568f" stroke-width="1.5"/><circle cx="190" cy="151" r="58" fill="#72568f" fill-opacity=".2" stroke="#72568f" stroke-width="1.5"/></svg><div class="art-caption">RELATED. DISTINCT. HUMAN.</div></div>`;
}
