import {cp,mkdir,readdir,readFile,writeFile,rm} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {resolve,relative,join} from 'node:path';
const root=resolve(import.meta.dirname,'..'),dest=join(root,'dist');
await rm(dest,{recursive:true,force:true});await mkdir(dest,{recursive:true});await cp(join(root,'app'),dest,{recursive:true});
async function walk(dir){let out=[];for(const ent of await readdir(dir,{withFileTypes:true})){const p=join(dir,ent.name);out.push(...(ent.isDirectory()?await walk(p):[p]));}return out;}
const files=(await walk(dest)).filter(p=>!p.endsWith('/sw.js')).sort();
const hash=createHash('sha256');for(const file of files)hash.update(await readFile(file));
const version=hash.digest('hex').slice(0,14),assets=files.map(p=>'./'+relative(dest,p));
const sw=`// Generated by scripts/build.mjs. Cache changes whenever app content changes.
const CACHE='four-tests-${version}';
const ASSETS=${JSON.stringify(['./',...assets])};
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('four-tests-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET'||new URL(event.request.url).origin!==self.location.origin)return;
 event.respondWith(caches.open(CACHE).then(async cache=>{
  const cached=await cache.match(event.request,{ignoreSearch:true});
  if(cached)return cached;
  try{return await fetch(event.request);}catch(err){if(event.request.mode==='navigate')return cache.match('./index.html');throw err;}
 }));
});
// Updates activate after existing app tabs close, avoiding mixed-version assessments.
`;
await writeFile(join(dest,'sw.js'),sw);await writeFile(join(dest,'.nojekyll'),'');
console.log(`Built ${files.length} assets, cache ${version}.`);
